import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/components/mainComponents/header/Header";
import ServiceWorkerRegister from "@/components/nestedComponents/serviceWorkerRegister/ServiceWorkerRegister";
import localFont from "next/font/local";

const myFont = localFont({
    src: [{ path: "../fonts/die-grotesk-b-regular.woff2" }],
    variable: "--font-main",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html lang="en" className={myFont.variable}>
            <body>
                <ServiceWorkerRegister />
                <Header />
                <main>{children}</main>
            </body>
        </html>
    );
}
